USE ProjectManagerDB;

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserName NVARCHAR(50) NOT NULL UNIQUE,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(64) NOT NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIMEOFFSET NOT NULL
);

CREATE TABLE Roles (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(20) NOT NULL
);

CREATE TABLE Permissions (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(30) NOT NULL
);

CREATE TABLE Priorities (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(20) NOT NULL UNIQUE,
    Level INT NOT NULL
);

CREATE TABLE Projects (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(30) NOT NULL UNIQUE,
    [Key] NVARCHAR(4) NOT NULL UNIQUE,
    IsDeleted BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIMEOFFSET NOT NULL
);

CREATE TABLE ProjectRoles (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ProjectId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(30) NOT NULL
);

CREATE TABLE ProjectRolePermissions (
    ProjectRoleId UNIQUEIDENTIFIER NOT NULL,
    PermissionId UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY (ProjectRoleId, PermissionId)
);

CREATE TABLE ProjectUserRoles (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ProjectId UNIQUEIDENTIFIER NOT NULL,
    ProjectRoleId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL
);

CREATE TABLE Tags (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ProjectId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(20) NOT NULL
);

CREATE TABLE Tickets (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ProjectId UNIQUEIDENTIFIER NOT NULL,
    PriorityId UNIQUEIDENTIFIER NOT NULL,
    AssigneeId UNIQUEIDENTIFIER NULL,
    ReporterId UNIQUEIDENTIFIER NOT NULL,
    Status INT NOT NULL,
    Resolution INT NOT NULL,
    TicketType INT NOT NULL,
    TicketNumber INT NOT NULL,
    Title NVARCHAR(255) NOT NULL,
    Description NVARCHAR(4000) NULL,
    Version NVARCHAR(50) NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIMEOFFSET NOT NULL,
);

CREATE TABLE Comments (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    TicketId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Content NVARCHAR(4000) NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL
);

CREATE TABLE TicketRelations (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    SourceId UNIQUEIDENTIFIER NOT NULL,
    TargetId UNIQUEIDENTIFIER NOT NULL,
    RelationType INT NOT NULL
);

CREATE TABLE TicketTags (
    TagId UNIQUEIDENTIFIER NOT NULL,
    TicketId UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY (TagId, TicketId)
);

CREATE TABLE UserRoles (
    UserId UNIQUEIDENTIFIER NOT NULL,
    RoleId UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY (UserId, RoleId)
);