USE ProjectManagerDB;

ALTER TABLE Comments
ADD CONSTRAINT FK_Comments_Tickets FOREIGN KEY (TicketId) REFERENCES Tickets(Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Comments_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE NO ACTION;

ALTER TABLE ProjectRoles
ADD CONSTRAINT FK_ProjectRoles_Projects FOREIGN KEY (ProjectId) REFERENCES Projects(Id) ON DELETE NO ACTION;

ALTER TABLE ProjectRolePermissions
ADD CONSTRAINT FK_ProjectRolePermissions_ProjectRoles FOREIGN KEY (ProjectRoleId) REFERENCES ProjectRoles(Id) ON DELETE NO ACTION,
    CONSTRAINT FK_ProjectRolePermissions_Permissions FOREIGN KEY (PermissionId) REFERENCES [Permissions](Id) ON DELETE NO ACTION;

ALTER TABLE ProjectUserRoles
ADD CONSTRAINT FK_ProjectUserRoles_Projects FOREIGN KEY (ProjectId) REFERENCES Projects(Id) ON DELETE NO ACTION,
    CONSTRAINT FK_ProjectUserRoles_ProjectRoles FOREIGN KEY (ProjectRoleId) REFERENCES ProjectRoles(Id) ON DELETE NO ACTION,
    CONSTRAINT FK_ProjectUserRoles_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE NO ACTION;

ALTER TABLE Tags
ADD CONSTRAINT FK_Tags_Projects FOREIGN KEY (ProjectId) REFERENCES Projects(Id) ON DELETE CASCADE;

ALTER TABLE Tickets
ADD CONSTRAINT FK_Tickets_Projects FOREIGN KEY (ProjectId) REFERENCES Projects(Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Tickets_Priorities FOREIGN KEY (PriorityId) REFERENCES Priorities(Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Tickets_Assignee FOREIGN KEY (AssigneeId) REFERENCES Users(Id) ON DELETE NO ACTION,
    CONSTRAINT FK_Tickets_Reporter FOREIGN KEY (ReporterId) REFERENCES Users(Id) ON DELETE NO ACTION;

ALTER TABLE TicketRelations
ADD CONSTRAINT FK_TicketRelations_Source FOREIGN KEY (SourceId) REFERENCES Tickets(Id) ON DELETE NO ACTION,
    CONSTRAINT FK_TicketRelations_Target FOREIGN KEY (TargetId) REFERENCES Tickets(Id) ON DELETE NO ACTION;

ALTER TABLE TicketTags
ADD CONSTRAINT FK_TicketTags_Tags FOREIGN KEY (TagId) REFERENCES Tags(Id) ON DELETE CASCADE,
    CONSTRAINT FK_TicketTags_Tickets FOREIGN KEY (TicketId) REFERENCES Tickets(Id) ON DELETE CASCADE;

ALTER TABLE UserRoles
ADD CONSTRAINT FK_UserRoles_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE NO ACTION,
    CONSTRAINT FK_UserRoles_Roles FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE NO ACTION;