USE ProjectManagerDB;

DENY INSERT, UPDATE, DELETE ON Permissions TO PUBLIC;
GRANT SELECT ON Permissions TO PUBLIC;

DENY INSERT, UPDATE, DELETE ON Roles TO PUBLIC;
GRANT SELECT ON Roles TO PUBLIC;

DENY DELETE ON Projects TO PUBLIC;
GRANT SELECT, INSERT, UPDATE ON Projects TO PUBLIC;

DENY DELETE ON Tickets TO PUBLIC;
GRANT SELECT, INSERT, UPDATE ON Tickets TO PUBLIC;

DENY DELETE ON Users TO PUBLIC;
GRANT SELECT, INSERT, UPDATE ON Users TO PUBLIC;